# Generated by Django 3.0.3 on 2020-05-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteitdown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(default='unKnown', max_length=20),
        ),
        migrations.AddField(
            model_name='notes',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
